# Assignment 1

### by Charan Lalchand Soneji

Pytorch is an open source library used for ML operations which was created by Facebook.
Some of the functions discussed are:
- torch.randn()
- torch.add()
- torch.clamp()
- torch.erf()
- torch.stack()

In [8]:
# Import torch and other required modules
import torch

## Function 1 - torch.randn()

This function is used to generate a tensor of size 'n', which is specified as a parameter in the function. The values obtained have an overall mean of 0 and a variance of 1.

In [16]:
# Example 1 - working example of torch.randn()
random=torch.randn(5)
print("List of random tensors generated are: {}".format(random))

List of random tensors generated are: tensor([ 0.0858,  0.0928,  0.1352,  2.0057, -1.1905])


Here, in the above example, we have specified a parameter of 5 inside our torch.randn() function which results in 5 randomly generated values.

In [18]:
# Example 2 - working
random=torch.randn(3,6)
print("Matrix of randomly generated tensors is given as:\n {}".format(random))

Matrix of randomly generated tensors is given as:
 tensor([[-0.0083, -0.6507, -0.4653, -0.1265, -0.8600, -0.9617],
        [ 1.8241, -0.2673,  0.4912, -1.8465,  0.3736, -1.1710],
        [-1.0676, -0.8678,  0.7998,  0.8005,  0.4656, -0.3603]])


So the randn() function can also be used in order to generate matrices of tensors which is done in the example. Here, we give in 2 arguments which represent the number of rows and columns of the matrix obtained. Like in the above example, it may be seen that 3 refers to the number of rows and 6 refers to the number of columns.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randn()

TypeError: randn() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


Here, in the above example, since we havent passed any parameters to the randn() function, it returns an error.

So the given function is used while setting a randomly given set of weights and biases just before the training of any model. Examples may be seen in the case of a linear regression model whereby weights and biases are set using rand() and a random set of matrix tensor is obtained.

## Function 2 - torch.add()

Used in order to add any 2 tensors within our eniroment. It can be used to perform operations to one tensor or to two tensors as well.

In [23]:
# Example 1 - working example of torch.add()
a=torch.randn(5)
print("Randonly generated tensor before addition: {}".format(a))
a=torch.add(a,20)
print("Tensor obtained after addition: {}".format(a))

Randonly generated tensor before addition: tensor([-1.3173,  0.4178,  0.4366, -0.6230,  1.0592])
Tensor obtained after addition: tensor([18.6827, 20.4178, 20.4366, 19.3769, 21.0592])


So in the given example, we have generated a random tensor with 5 values and performed scalar addition to it. Whenever a single tensor is passed to the function along with a scalar value, scalar addition to each of the values of the tensor is perfomed.

In [26]:
# Example 2 - working
a=torch.randn(4)
print("Randomly generated tensor a: {}".format(a))
b=torch.randn(5,1)
print("Randomly generated tensor b: {}".format(b))
print("On addition of 'a' with scalar multiple of 10 with 'b':\n{}".format(torch.add(a,b,alpha=10)))

Randomly generated tensor a: tensor([ 0.6545, -0.9548,  0.4864,  0.8644])
Randomly generated tensor b: tensor([[-0.3637],
        [-1.5847],
        [-0.8539],
        [ 0.4287],
        [ 1.1599]])
On addition of 'a' with scalar multiple of 10 with 'b':
tensor([[ -2.9824,  -4.5918,  -3.1505,  -2.7726],
        [-15.1927, -16.8020, -15.3607, -14.9828],
        [ -7.8848,  -9.4941,  -8.0529,  -7.6749],
        [  4.9414,   3.3320,   4.7733,   5.1512],
        [ 12.2533,  10.6439,  12.0852,  12.4631]])


We have declared a 1 dimension tensor as a and a 2 dimension tensor as b which is then multiplied using scalar multiplication with 'alpha' which is a given parameter of torch.add()

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.randn(4)
b=torch.randn(5,3)
torch.add(a,b)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

Here, since the size of the two tensors is not the same, they cannot be simply added.

Whenever the weights or bias have to be altered after a specific iteration or epoch in a enviroment, they can be done with the help of this function.

## Function 3 - torch.clamp()

It basically ensures that all the values in the tensor are within a given specific range and does nto exceed that. For the values that do go beyond range, they are modified to the limit.

In [30]:
# Example 1 - working exmaple of torch.clamp()
a=torch.randn(5)
print("Randomly generated tensor 'a': {}".format(a))
print("Values after clamping are: {}".format(torch.clamp(a,min=.2,max=.5)))

Randomly generated tensor 'a': tensor([ 0.3519, -1.1533,  0.9021,  0.2696,  0.3591])
Values after clamping are: tensor([0.3519, 0.2000, 0.5000, 0.2696, 0.3591])


So we want to ensure that the values are between 0.2 and 0.5 and the following parameters have been given to the torch.clamp() function.

In [35]:
# Example 2 - working
a=torch.randn(5)
print("Randomly generated tensor 'a': {}".format(a))
print("Values after clamping are: {}".format(torch.clamp(a,max=.5)))

Randomly generated tensor 'a': tensor([ 0.0317,  1.4063,  0.1407, -0.3402,  1.4409])
Values after clamping are: tensor([ 0.0317,  0.5000,  0.1407, -0.3402,  0.5000])


Since we are only mentioning the upper limit of 0.5, it clamps all the values greater than 0.5 to be 0.5 and does not affect the lower values.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.randn(5)
torch.clamp(a)

RuntimeError: At least one of 'min' or 'max' must not be None

When the attributes of min and max are not specified, it is not known about the parameters to which the tensor is to be clamped.

Whenever the values are required to be within a given range, the clamp function is to be used.

## Function 4 - torch.erf()

It provides the error functions of each of the the tensor values.
It is an inbuilt module of torch which saves us time by easing the calculation part.

In [41]:
# Example 1 - working example of torch.erf()
a=torch.randn(5)
print("Randomly generated tensor:\n{}".format(a))
print("The error function of each of the values is given by the following resultant tensor:\n {}".format(torch.erf(a)))

Randomly generated tensor:
tensor([ 0.4616, -0.8944, -1.6780, -0.7144,  1.1185])
The error function of each of the values is given by the following resultant tensor:
 tensor([ 0.4862, -0.7941, -0.9824, -0.6876,  0.8863])


The error function is given by a fixed formula and the torch.erf() contains of a single argument which is the tensor itself and it outputs the tensor whereby each value represents the error value calculated.

In [42]:
# Example 2 - working
a=torch.randn(5)
print("Randomly generated tensor:\n{}".format(a))
print("The 'inverse error function' of each of the values is given by the following resultant tensor:\n {}".format(torch.erfinv(a)))

Randomly generated tensor:
tensor([-0.3974, -1.8043,  2.7671, -1.3477, -0.0359])
The 'inverse error function' of each of the values is given by the following resultant tensor:
 tensor([-0.3682,     nan,     nan,     nan, -0.0318])


In the above example we have calculated the Inverse error function using the formula which returns a value of (-infinity) which is not displayabel hence the output given is NaN

In [43]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.randn(5)
torch.erf()

TypeError: erf() missing 1 required positional arguments: "input"

When the parameter or argument of the tensor is not passed in order to evaluate the error function, an error is thrown.

Can be used to calculate the error function during evaluation of our model but in most cases, the error function from the module Torch.nn is preferred or our own error function can be made use of.

## Function 5 - torch.stack()

According to the documentation, it concatenates sequence of tensors along a new dimension as long as these tensors are of equal size.

In [47]:
# Example 1 - working
a=torch.randn(2,3)
print("Random generated tensor a: {}".format(a))
b=torch.randn(2,3)
print("Random generated tensor b: {}".format(b))
c=torch.randn(2,3)
print("Random generated tensor c: {}".format(c))
print("The stack obtained from tensors are: \n{}".format(torch.stack([a,b,c]).shape))

Random generated tensor a: tensor([[ 0.9872, -1.0135, -1.3007],
        [-0.3488, -0.0740,  0.3266]])
Random generated tensor b: tensor([[ 0.4768,  2.2769, -0.4442],
        [-0.6516,  0.3097,  0.7242]])
Random generated tensor c: tensor([[ 1.1128, -1.2929, -1.2215],
        [-0.8428, -0.2639,  0.3746]])
The stack obtained from tensors are: 
torch.Size([3, 2, 3])


So the stack size represents a tuple with 3 arguments: (a,b,c) where a represents the number of tensors, b represents the number of rows and c represents the number of columns. It is to be noted that b and c have to have the same value in order to make use of the stack function.

In [50]:
# Example 2 - working
a=torch.randn(3,3)
b=torch.randn(3,3)
print("Stacked tensors are shown by:\n{}".format(torch.stack([a,b])))

Stacked tensors are shown by:
tensor([[[ 0.8187, -0.4476,  1.0783],
         [-0.0620, -0.3029,  0.3287],
         [-0.4454,  2.2939,  0.6369]],

        [[-0.1665, -0.7349,  0.3001],
         [ 0.6647,  3.3316,  1.9687],
         [-0.9410,  0.5416,  0.1764]]])


Here the stacks are represented of the two randomly generated tensors.

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.randn(4,5)
b=torch.randn(3,7)
print("Stacked tensors are shown by:\n{}".format(torch.stack([a,b])))

RuntimeError: stack expects each tensor to be equal size, but got [4, 5] at entry 0 and [3, 7] at entry 1

Here, the tensors are of different dimension, hence while trying to combine them into a single stack tensor, we obtain an error.

When multiple epochs are to be carried out and the weights or bias'es are to be kept track of, a stack can be used which will keep appending the values of the weight or bias and would not throw an error since its dimension remains constant.

## Conclusion

In this notebook, we have discussed a number of functions which we would commonly as we work with models and training throughout. Some of the main functions include, add(), stack(), randn(), clamp() and erf(). Once we have fammiliarized ourselves with these algos, we can move to working with understanding of ML based algorithms and models.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* This is something i read of `erf and erfinv`: https://discuss.pytorch.org/t/erf-and-erfinv-functions-in-pytorch/1313/6
* Din't find the documentation of `stacks` to be explanatory hence I used this: https://stackoverflow.com/questions/52288635/how-to-use-torch-stack-function

In [52]:
!pip install jovian --upgrade --quiet

In [53]:
import jovian

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "charan-soneji-cls/01-tensor-operations-ba06f" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/charan-soneji-cls/01-tensor-operations-ba06f


'https://jovian.ml/charan-soneji-cls/01-tensor-operations-ba06f'